[문제-1] 길이가 10인 0-벡터를 만드세요.

In [4]:
import numpy as np
a = np.zeros(10, dtype = int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


[문제-2] 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [5]:
a = np.zeros(10, dtype = int)
a[4] = 1
print(a)

[0 0 0 0 1 0 0 0 0 0]


 [문제-3] 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [6]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


[문제-4] 위 벡터의 순서를 바꾸세요.

In [7]:
a = np.arange(10,50)
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [49]:
a = np.arange(49,9,-1)
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


 [문제-5] 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [14]:
a = np.arange(0,9)
b= a.reshape((3,3))
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[문제-6] 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [19]:
a = np.array([1,2,0,0,4,0])
print(a)
print(a != 0)
print( a[a != 0] )

[1 2 0 0 4 0]
[ True  True False False  True False]
[1 2 4]


 [문제-7] 3x3 단위 행렬(identity matrix)을 만드세요

In [22]:
print(np.identity(3)) #np.eye (직사각형 형태의 단위행렬을 만들 수 있고 위치 값 지정가능)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[문제-8] 난수 원소를 가지는 3x3 행렬을 만드세요

In [23]:
a = np.random.rand(3,3)
print(a)

[[0.08592236 0.12816852 0.01452663]
 [0.13417489 0.13328951 0.63804346]
 [0.12147017 0.20984196 0.79415371]]


[문제-9] 위에서 만든 난수 행렬에서 최대값/최솟값 원소를 찾으세요.

In [24]:
print(np.max(a))
print(np.min(a))

0.7941537059480612
0.014526626611991444


[문제-10] 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [25]:
# 행 평균
print(np.mean(a, axis = 1))
# 열 평균
print(np.mean(a, axis =0))

[0.07620584 0.30183595 0.37515528]
[0.11385581 0.1571     0.48224126]


[문제-11] 5x5짜리 정방행렬의 단위행렬을 생성하시오

In [50]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


 [문제-12] 10~50까지 값 9개를 정수로 발생시켜 출력

In [51]:
data = np.random.randint(1,51,size = 9)
print(data)

[ 4 24  1 30 11  4 44 31  5]


[문제-13] '문제-12' 배열의 shape을 3x3으로 변환

In [52]:
d = data.reshape((3,3))
print(d)

[[ 4 24  1]
 [30 11  4]
 [44 31  5]]


 [문제-14] '문제-13' 배열의 각 행끼리의 합을 구하여 출력

In [53]:
print(np.sum(d, axis = 1))

[29 45 80]


[문제-15] '문제-13' 배열의 각 열 중 최대값 구하여 출력

In [54]:
print(np.max(d, axis = 0))

[44 31  5]


[문제-16] '문제-13' 배열의 전체 요소의 평균을 구하여 출력

In [55]:
print(np.mean(d))

17.11111111111111


 [문제-17] 1~10 사이의 정수를 요소로 하는 2x3 배열 생성

In [56]:
k= np.random.randint(1,11,size = (2,3))
print(k)

[[ 9  7 10]
 [ 6 10  7]]


 [문제-18] 10~20 사이의 정수를 요소로 하는 3x2 배열 생성

In [57]:
z= np.random.randint(10,21,size = (3,2))
print(z)

[[12 13]
 [14 20]
 [12 17]]


 [문제-19] '문제-17'과 '문제-18'의 두 배열의 행렬 곱을 구하여 출력

In [58]:
f= k@z
print(f)

[[326 427]
 [296 397]]


[문제-20] '문제-19' 배열의 전치 행렬을 구하여 출력

In [60]:
print(f.T)
print(f.transpose())

[[326 296]
 [427 397]]
[[326 296]
 [427 397]]


[문제-21] 로또 번호 생성하기 (1~46 사이의 중복되지 않은 정수 6개 추출)

In [61]:
b = np.random.choice(np.arange(1,46), size = 6, replace= False) 
#replace = False ==  비복원추출 / default -> True(복원추출)
print(b)

[37 21  5 13 20  2]
