# [문제] BMI 지수 계산 및 과체중 이상인 BMI 값 확인
- 10명에 대한 키와 몸무게가 들어있는 'height_weight.txt'를 읽어 각 사람별 BMI 지수를 구하고 비만 전단계 이상인 BMI 값 확인하기

<pre>
 BMI 지수 = 몸무게(kg) / 키(M)의 제곱
 체질량지수의 범위 값에 따른 비만도 값 지정
 18.5 미만 ▶ 저체중
 18.5 ~ 22.9 ▶ 정상
 23 ~ 24.9 ▶ 비만 전단계
 25 ~ 29 ▶ 1단계 비만
 30 ~ 34.9 ▶ 2단계 비만
 35이상 ▶ 고도비만
</pre>

In [24]:
import numpy as np
data = np.loadtxt('height_weight.txt', delimiter= ',', dtype = float)
print(data)
print(type(data))
kg_cm[0]*0.01
m = np.array(kg_cm[0]*0.01)
kg = np.array(kg_cm[1])
BMI = kg / m**2
print('-'*30)
print(BMI)
print('-'*30)
print(BMI[BMI>=23])
print('-'*30)
print(BMI[np.logical_and(BMI>=22, BMI<=24)])

[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]
<class 'numpy.ndarray'>
------------------------------
[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]
------------------------------
[27.07018468 25.86122449 24.20652885 23.14392095 23.62028791 25.59220998]
------------------------------
[23.14392095 23.62028791]


# [문제] 국가건강검진 혈압혈당 데이터 분석

* '국가건강검진_혈압혈당데이터.csv' 파일 내용을 읽기 <data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", dtype=np.float, skiprows=1)>
    - 성별: 1(남자), 2(여자)
    - 연령그룹: 1(20-24), 2(25-26),...25-74세까지 2살 간격으로 1개 그룹으로 지정, 27(74세 이상)
    - 고혈압 당뇨병 진료여부: 1(고혈압 및 당뇨진료내역 있음), 2(고혈압 진료내역 있음), 3(당뇨 진료내역 있음), 4(고혈압 및 당뇨 진료내역 없음)
    - 정상혈압: 수축기 혈압 120nnHg 미만, 확장기 혈압 80mmHg 미만
    - 공복혈당 수치: 126 mg/dL 이상 -> 당뇨병, 100mg/dL-> 정상
* 전체 레코드 수와 상위 5개 데이터 확인
* 데이터 모양 확인
* 여성과 남성의 데이터 수 확인
* 여성과 남성의 수축기혈압과 이완기혈압의 평균값 확인
* 정상 혈압 남자 및 여자 수 확인
* 당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수

In [7]:
import numpy as np
data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", dtype=float, skiprows=1)
print(f'전체 레코드 수: {len(data):,}개')
print('탑 5:',data[:5])
print('데이터 모양 획인:', data.shape)
print('여성과 남성의 데이터 수 확인')
print(f'남성 수:{np.sum(data[: ,0]==1):,}개')
print(f'여성 수:{np.sum(data[: ,0]==2):,}개')

전체 레코드 수: 1,000,000개
탑 5: [[  1.    1.  116.   78.   94.    4.   16.6]
 [  1.    1.  100.   60.   79.    4.   22.3]
 [  1.    1.  100.   60.   87.    4.   21.9]
 [  1.    1.  111.   70.   72.    4.   20.2]
 [  1.    1.  120.   80.   98.    4.   20. ]]
데이터 모양 획인: (1000000, 7)
여성과 남성의 데이터 수 확인
남성 수:510,227개
여성 수:489,773개


In [6]:
# 각 컬럼별 unique  값 확인
print('성별 값: ', np.unique(data[:,0]))
# 성별의 컬럼은 1과 2의 데이터가 있다.

print('고열합,당뇨병 진료 여부 값', np.unique(data[:,5]) )

성별 값:  [1. 2.]
고열합,당뇨병 진료 여부 값 [1. 2. 3. 4.]


In [10]:
# 수축기 혈압 : SBP
# 이완기 혈압 : DBP
print('남성의 수축기혈압 평균')
print(f'{np.mean(data[data[: ,0]==1], axis = 0)[2]:.2f}')
print(f'{np.mean(data[data[: ,0]==1][:,2]):.2f}')
print('남성의 이완기혈압 평균')
print(np.mean(data[data[: ,0]==1], axis = 0)[3])
print(f'{np.mean(data[data[: ,0]==1][:,3]):.2f}')

print('여성의 수축기혈압 평균')
print(f'{np.mean(data[data[: ,0]==2], axis = 0)[2]:.2f}')
print(f'{np.mean(data[data[: ,0]==2][:,2]):.2f}')
print('여성의 이완기혈압 평균')
print(np.mean(data[data[: ,0]==2], axis = 0)[3])
print(f'{np.mean(data[data[: ,0]==2][:,3]):.2f}')
#np.where(np.max(a)==a)
# 상혈압: 수축기 혈압 120nnHg 미만, 확장기 혈압 80mmHg 미만
man_s = data[data[: ,0]==1][:,2]
man_e = data[data[: ,0]==1][:,3]
print('정상 혈압 남자 수', np.sum(np.logical_and(man_s<120, man_e<80)))

woman_s = data[data[: ,0]==2][:,2]
woman_e = data[data[: ,0]==2][:,3]
print('정상 혈압 여자 수', np.sum(np.logical_and(woman_s<120, woman_e<80)))

#공복혈당 수치: 126 mg/dL 이상 -> 당뇨병, 100mg/dL-> 정상
print('당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수:')
print(f'{np.mean(data[data[:,4]>=126][:,-1]):.2f}')
print(f'{np.mean(data[data[:,4]>=126], axis =0)[-1]:.2f}')

남성의 수축기혈압 평균
124.28
124.28
남성의 이완기혈압 평균
77.61497725522169
77.61
여성의 수축기혈압 평균
119.36
119.36
여성의 이완기혈압 평균
73.88446688567969
73.88
정상 혈압 남자 수 158007
정상 혈압 남자 수 230707
당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수:
25.17
25.17


# [문제] 시에틀 강수량 데이터 분석
- 'Seattle2014.csv' 파일 내용 읽기
- 강수량('PRCP')이 많은 날 상위 10일 확인
- 1월 강수량만 출력
- 1월에 내린 강수량의 합, 평균강수량 확인
- 1년동안 강수량이 40미만으로 내린 날이 몇일인가?

In [21]:
import numpy as np
data = np.loadtxt('Seattle2014.csv', delimiter=',', dtype = 'object', skiprows=1 )
#모든 데이터를 문자열로 읽어오기 위해서 dtype을 object로 지정
PRCP_Date =np.array(data[:,[2,3]], dtype = int)

print ("강수량('PRCP')이 많은 날 상위 10일 확인")
PRCP = PRCP_Date[:,1]
idx = np.argsort(PRCP)[::-1]
print(PRCP_Date[idx][:11])
#np.sort(data)[::-1] 


print('1월에 내린 강수량의 합, 평균강수량 확인')
print('방법 1')
Date = PRCP_Date [:,0]
print('합:',np.sum((PRCP_Date[Date<=20140131])[:,1]))
print('평균:',np.mean((PRCP_Date[np.logical_and(Date>=20140101,Date<=20140131)])[:,1]))

print('방법 2')
temp = np.array([[date[4:6],prcp]for date, prcp in data[:,[2,3]]])
jan_prcp = temp[temp[:,0]=='01'][:,1].astype(int)
print(jan_prcp)
print('합:',np.sum(jan_prcp))
print('평균:',np.mean(jan_prcp))

print('1년동안 강수량이 40미만으로 내린 날이 몇일인가')
PRC_ind = PRCP<40
print(np.sum(PRC_ind))
print(len(PRCP_Date[PRC_ind]))
#bolean 인덱싱 True and False
#필터링 된 데이터

강수량('PRCP')이 많은 날 상위 10일 확인
[[20140305      467]
 [20141128      343]
 [20140503      333]
 [20140308      323]
 [20141022      320]
 [20140316      277]
 [20140216      264]
 [20141030      254]
 [20140328      221]
 [20140129      216]
 [20140813      216]]
1월에 내린 강수량의 합, 평균강수량 확인
방법 1
합: 940
평균: 30.322580645161292
방법 2
[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]
합: 940
평균: 30.322580645161292
1년동안 강수량이 40미만으로 내린 날이 몇일인가
277
277


In [20]:
my_list = np.array([[str(date)[4:6],prcp]for date, prcp in PRCP_Date])
print(np.mean(my_list[my_list[:,0]=='01'][:,1].astype(int)))
print(np.sum(my_list[my_list[:,0]=='01'][:,1].astype(int)))

30.322580645161292
940


# [문제] 영화 평점 분석
- 'ratings.dat' 파일 내용 읽기 (데이터 형식: user_id::item_id::rating::timestamp)
- 상위 10개 데이터 출력하기
- 데이터 정보 확인(크기, 차원)
- 전체 데이터 평점 구하기
- 사용자 아이디 1인 데이터 출력하기
- 사용자 아이디 1인 사람의 평점 평균 구하기
- 각 사용자별 평점 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
- 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기

In [141]:
import numpy as np
data = np.loadtxt('ratings.dat', delimiter='::', dtype = int)
print('상위 10개 데이터 출력하기')
ratings = data[:,2]
ratings_idx = np.argsort(ratings)[::-1]
print(ratings)
print(data[ratings_idx][:11])



상위 10개 데이터 출력하기
[5 3 3 ... 5 4 4]
[[        1      1193         5 978300760]
 [     4518      3429         5 964843900]
 [     4516       924         5 964856468]
 [     1906      2176         5 974690515]
 [     4516       296         5 964856871]
 [     4516      2858         5 964856837]
 [     4516       608         5 964856837]
 [     4516      1148         5 964856356]
 [     4516      2890         5 964856902]
 [     4516      2132         5 964856665]
 [     1906       480         5 974690983]]


In [146]:
print('전체 데이터 평점 구하기')
print(f'{np.mean(ratings):.2f}')

print( '사용자 아이디 1인 데이터 출력하기')
user_id = data[:,0]
print(data[user_id==1])

전체 데이터 평점 구하기
3.58
사용자 아이디 1인 데이터 출력하기
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1    

In [148]:
print('사용자 아이디 1인 사람의 평점 평균 구하기')
print(f'{np.mean(data[user_id==1][:,2]):.2f}')



사용자 아이디 1인 사람의 평점 평균 구하기
4.19


In [151]:
print('각 사용자별 평점 평균 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)')
for i in np.unique(user_id):
    print(f'id = {i}, 평점 평균 ={ np.mean(data[user_id == i ][:,2]):.2f}')

id_avg_rating = np.array([[id, np.mean(data[user_id == id][:,2])]for id in np.unique(user_id)])
#print(id_avg_rating)

각 사용자별 평점 평균 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
id = 1, 평점 평균 =4.19
id = 2, 평점 평균 =3.71
id = 3, 평점 평균 =3.90
id = 4, 평점 평균 =4.19
id = 5, 평점 평균 =3.15
id = 6, 평점 평균 =3.90
id = 7, 평점 평균 =4.32
id = 8, 평점 평균 =3.88
id = 9, 평점 평균 =3.74
id = 10, 평점 평균 =4.11
id = 11, 평점 평균 =3.28
id = 12, 평점 평균 =3.83
id = 13, 평점 평균 =3.39
id = 14, 평점 평균 =3.32
id = 15, 평점 평균 =3.32
id = 16, 평점 평균 =3.03
id = 17, 평점 평균 =4.08
id = 18, 평점 평균 =3.65
id = 19, 평점 평균 =3.57
id = 20, 평점 평균 =4.08
id = 21, 평점 평균 =2.91
id = 22, 평점 평균 =3.07
id = 23, 평점 평균 =3.32
id = 24, 평점 평균 =3.95
id = 25, 평점 평균 =3.74
id = 26, 평점 평균 =2.96
id = 27, 평점 평균 =4.17
id = 28, 평점 평균 =3.76
id = 29, 평점 평균 =3.58
id = 30, 평점 평균 =3.49
id = 31, 평점 평균 =3.73
id = 32, 평점 평균 =3.62
id = 33, 평점 평균 =3.50
id = 34, 평점 평균 =3.87
id = 35, 평점 평균 =3.54
id = 36, 평점 평균 =4.20
id = 37, 평점 평균 =3.70
id = 38, 평점 평균 =3.58
id = 39, 평점 평균 =3.56
id = 40, 평점 평균 =3.45
id = 41, 평점 평균 =3.48
id = 42, 평점 평균 =3.74
id = 43, 평점 평균 =4.12
id = 44, 평점 평균 =3.63
id = 45, 평점 평균 =2.95
id = 46

id = 377, 평점 평균 =3.90
id = 378, 평점 평균 =3.51
id = 379, 평점 평균 =4.23
id = 380, 평점 평균 =3.72
id = 381, 평점 평균 =4.11
id = 382, 평점 평균 =4.02
id = 383, 평점 평균 =3.57
id = 384, 평점 평균 =3.59
id = 385, 평점 평균 =3.96
id = 386, 평점 평균 =3.32
id = 387, 평점 평균 =3.68
id = 388, 평점 평균 =3.88
id = 389, 평점 평균 =3.56
id = 390, 평점 평균 =3.67
id = 391, 평점 평균 =3.73
id = 392, 평점 평균 =3.47
id = 393, 평점 평균 =3.58
id = 394, 평점 평균 =3.34
id = 395, 평점 평균 =3.61
id = 396, 평점 평균 =3.56
id = 397, 평점 평균 =3.88
id = 398, 평점 평균 =3.81
id = 399, 평점 평균 =4.16
id = 400, 평점 평균 =3.88
id = 401, 평점 평균 =3.87
id = 402, 평점 평균 =3.59
id = 403, 평점 평균 =3.80
id = 404, 평점 평균 =4.14
id = 405, 평점 평균 =3.80
id = 406, 평점 평균 =3.31
id = 407, 평점 평균 =3.44
id = 408, 평점 평균 =4.35
id = 409, 평점 평균 =3.92
id = 410, 평점 평균 =3.97
id = 411, 평점 평균 =3.28
id = 412, 평점 평균 =4.40
id = 413, 평점 평균 =4.40
id = 414, 평점 평균 =3.07
id = 415, 평점 평균 =3.87
id = 416, 평점 평균 =3.76
id = 417, 평점 평균 =4.05
id = 418, 평점 평균 =3.55
id = 419, 평점 평균 =3.96
id = 420, 평점 평균 =4.36
id = 421, 평점 평균 =4.25
id = 422, 

id = 809, 평점 평균 =4.03
id = 810, 평점 평균 =3.82
id = 811, 평점 평균 =4.18
id = 812, 평점 평균 =3.74
id = 813, 평점 평균 =3.34
id = 814, 평점 평균 =4.06
id = 815, 평점 평균 =4.07
id = 816, 평점 평균 =3.70
id = 817, 평점 평균 =4.01
id = 818, 평점 평균 =3.73
id = 819, 평점 평균 =3.32
id = 820, 평점 평균 =3.41
id = 821, 평점 평균 =2.95
id = 822, 평점 평균 =3.72
id = 823, 평점 평균 =3.87
id = 824, 평점 평균 =3.65
id = 825, 평점 평균 =3.62
id = 826, 평점 평균 =3.29
id = 827, 평점 평균 =3.95
id = 828, 평점 평균 =3.44
id = 829, 평점 평균 =4.23
id = 830, 평점 평균 =3.61
id = 831, 평점 평균 =4.11
id = 832, 평점 평균 =3.56
id = 833, 평점 평균 =4.05
id = 834, 평점 평균 =4.16
id = 835, 평점 평균 =2.75
id = 836, 평점 평균 =2.40
id = 837, 평점 평균 =3.26
id = 838, 평점 평균 =4.09
id = 839, 평점 평균 =3.99
id = 840, 평점 평균 =4.22
id = 841, 평점 평균 =3.58
id = 842, 평점 평균 =3.84
id = 843, 평점 평균 =3.94
id = 844, 평점 평균 =3.45
id = 845, 평점 평균 =3.98
id = 846, 평점 평균 =3.92
id = 847, 평점 평균 =3.61
id = 848, 평점 평균 =4.18
id = 849, 평점 평균 =3.26
id = 850, 평점 평균 =3.56
id = 851, 평점 평균 =3.59
id = 852, 평점 평균 =4.12
id = 853, 평점 평균 =3.89
id = 854, 

id = 1186, 평점 평균 =4.30
id = 1187, 평점 평균 =3.39
id = 1188, 평점 평균 =4.16
id = 1189, 평점 평균 =3.76
id = 1190, 평점 평균 =4.04
id = 1191, 평점 평균 =4.30
id = 1192, 평점 평균 =4.38
id = 1193, 평점 평균 =2.78
id = 1194, 평점 평균 =3.33
id = 1195, 평점 평균 =3.72
id = 1196, 평점 평균 =3.88
id = 1197, 평점 평균 =4.17
id = 1198, 평점 평균 =3.66
id = 1199, 평점 평균 =3.63
id = 1200, 평점 평균 =3.56
id = 1201, 평점 평균 =3.58
id = 1202, 평점 평균 =3.54
id = 1203, 평점 평균 =3.71
id = 1204, 평점 평균 =3.49
id = 1205, 평점 평균 =3.94
id = 1206, 평점 평균 =3.56
id = 1207, 평점 평균 =2.39
id = 1208, 평점 평균 =4.02
id = 1209, 평점 평균 =3.41
id = 1210, 평점 평균 =3.90
id = 1211, 평점 평균 =3.86
id = 1212, 평점 평균 =3.86
id = 1213, 평점 평균 =4.04
id = 1214, 평점 평균 =3.02
id = 1215, 평점 평균 =4.03
id = 1216, 평점 평균 =3.69
id = 1217, 평점 평균 =4.24
id = 1218, 평점 평균 =3.46
id = 1219, 평점 평균 =3.62
id = 1220, 평점 평균 =3.35
id = 1221, 평점 평균 =3.96
id = 1222, 평점 평균 =3.22
id = 1223, 평점 평균 =3.92
id = 1224, 평점 평균 =4.05
id = 1225, 평점 평균 =4.04
id = 1226, 평점 평균 =3.29
id = 1227, 평점 평균 =3.79
id = 1228, 평점 평균 =3.78
id = 1229, 

id = 1565, 평점 평균 =3.74
id = 1566, 평점 평균 =3.50
id = 1567, 평점 평균 =3.89
id = 1568, 평점 평균 =4.00
id = 1569, 평점 평균 =4.59
id = 1570, 평점 평균 =3.55
id = 1571, 평점 평균 =3.95
id = 1572, 평점 평균 =3.18
id = 1573, 평점 평균 =3.69
id = 1574, 평점 평균 =3.60
id = 1575, 평점 평균 =3.87
id = 1576, 평점 평균 =3.88
id = 1577, 평점 평균 =4.10
id = 1578, 평점 평균 =4.16
id = 1579, 평점 평균 =3.45
id = 1580, 평점 평균 =3.54
id = 1581, 평점 평균 =3.22
id = 1582, 평점 평균 =3.64
id = 1583, 평점 평균 =3.73
id = 1584, 평점 평균 =3.33
id = 1585, 평점 평균 =3.61
id = 1586, 평점 평균 =4.42
id = 1587, 평점 평균 =3.33
id = 1588, 평점 평균 =4.17
id = 1589, 평점 평균 =3.78
id = 1590, 평점 평균 =4.00
id = 1591, 평점 평균 =4.34
id = 1592, 평점 평균 =3.62
id = 1593, 평점 평균 =3.04
id = 1594, 평점 평균 =3.73
id = 1595, 평점 평균 =4.05
id = 1596, 평점 평균 =3.57
id = 1597, 평점 평균 =3.56
id = 1598, 평점 평균 =3.49
id = 1599, 평점 평균 =3.30
id = 1600, 평점 평균 =3.43
id = 1601, 평점 평균 =3.91
id = 1602, 평점 평균 =4.10
id = 1603, 평점 평균 =3.84
id = 1604, 평점 평균 =4.17
id = 1605, 평점 평균 =3.31
id = 1606, 평점 평균 =3.79
id = 1607, 평점 평균 =3.18
id = 1608, 

id = 1936, 평점 평균 =3.71
id = 1937, 평점 평균 =3.18
id = 1938, 평점 평균 =3.13
id = 1939, 평점 평균 =3.78
id = 1940, 평점 평균 =4.67
id = 1941, 평점 평균 =3.05
id = 1942, 평점 평균 =2.86
id = 1943, 평점 평균 =3.62
id = 1944, 평점 평균 =3.91
id = 1945, 평점 평균 =2.79
id = 1946, 평점 평균 =3.86
id = 1947, 평점 평균 =3.95
id = 1948, 평점 평균 =3.11
id = 1949, 평점 평균 =4.18
id = 1950, 평점 평균 =3.52
id = 1951, 평점 평균 =3.02
id = 1952, 평점 평균 =3.49
id = 1953, 평점 평균 =3.79
id = 1954, 평점 평균 =3.93
id = 1955, 평점 평균 =3.55
id = 1956, 평점 평균 =3.12
id = 1957, 평점 평균 =3.94
id = 1958, 평점 평균 =3.27
id = 1959, 평점 평균 =4.51
id = 1960, 평점 평균 =3.87
id = 1961, 평점 평균 =3.55
id = 1962, 평점 평균 =2.67
id = 1963, 평점 평균 =4.18
id = 1964, 평점 평균 =3.64
id = 1965, 평점 평균 =3.12
id = 1966, 평점 평균 =4.36
id = 1967, 평점 평균 =3.54
id = 1968, 평점 평균 =2.76
id = 1969, 평점 평균 =3.82
id = 1970, 평점 평균 =3.58
id = 1971, 평점 평균 =4.27
id = 1972, 평점 평균 =4.41
id = 1973, 평점 평균 =3.84
id = 1974, 평점 평균 =3.76
id = 1975, 평점 평균 =3.84
id = 1976, 평점 평균 =3.89
id = 1977, 평점 평균 =3.63
id = 1978, 평점 평균 =3.47
id = 1979, 

id = 2324, 평점 평균 =4.03
id = 2325, 평점 평균 =3.36
id = 2326, 평점 평균 =3.89
id = 2327, 평점 평균 =3.34
id = 2328, 평점 평균 =3.29
id = 2329, 평점 평균 =3.38
id = 2330, 평점 평균 =3.01
id = 2331, 평점 평균 =4.21
id = 2332, 평점 평균 =4.07
id = 2333, 평점 평균 =3.71
id = 2334, 평점 평균 =3.73
id = 2335, 평점 평균 =3.71
id = 2336, 평점 평균 =3.95
id = 2337, 평점 평균 =4.18
id = 2338, 평점 평균 =3.85
id = 2339, 평점 평균 =4.96
id = 2340, 평점 평균 =4.36
id = 2341, 평점 평균 =3.28
id = 2342, 평점 평균 =3.82
id = 2343, 평점 평균 =4.19
id = 2344, 평점 평균 =3.44
id = 2345, 평점 평균 =3.74
id = 2346, 평점 평균 =3.65
id = 2347, 평점 평균 =3.91
id = 2348, 평점 평균 =3.15
id = 2349, 평점 평균 =3.10
id = 2350, 평점 평균 =3.86
id = 2351, 평점 평균 =3.45
id = 2352, 평점 평균 =2.71
id = 2353, 평점 평균 =3.61
id = 2354, 평점 평균 =3.62
id = 2355, 평점 평균 =3.56
id = 2356, 평점 평균 =3.62
id = 2357, 평점 평균 =3.93
id = 2358, 평점 평균 =3.86
id = 2359, 평점 평균 =3.63
id = 2360, 평점 평균 =3.59
id = 2361, 평점 평균 =3.61
id = 2362, 평점 평균 =3.73
id = 2363, 평점 평균 =4.58
id = 2364, 평점 평균 =4.14
id = 2365, 평점 평균 =4.19
id = 2366, 평점 평균 =3.39
id = 2367, 

id = 2700, 평점 평균 =3.39
id = 2701, 평점 평균 =3.22
id = 2702, 평점 평균 =2.41
id = 2703, 평점 평균 =3.68
id = 2704, 평점 평균 =4.04
id = 2705, 평점 평균 =4.09
id = 2706, 평점 평균 =4.08
id = 2707, 평점 평균 =3.52
id = 2708, 평점 평균 =3.08
id = 2709, 평점 평균 =2.75
id = 2710, 평점 평균 =3.20
id = 2711, 평점 평균 =2.50
id = 2712, 평점 평균 =3.94
id = 2713, 평점 평균 =2.72
id = 2714, 평점 평균 =3.55
id = 2715, 평점 평균 =3.33
id = 2716, 평점 평균 =3.75
id = 2717, 평점 평균 =3.76
id = 2718, 평점 평균 =3.87
id = 2719, 평점 평균 =4.15
id = 2720, 평점 평균 =3.05
id = 2721, 평점 평균 =3.82
id = 2722, 평점 평균 =3.43
id = 2723, 평점 평균 =3.43
id = 2724, 평점 평균 =3.81
id = 2725, 평점 평균 =3.63
id = 2726, 평점 평균 =4.60
id = 2727, 평점 평균 =3.35
id = 2728, 평점 평균 =3.36
id = 2729, 평점 평균 =4.48
id = 2730, 평점 평균 =3.98
id = 2731, 평점 평균 =4.27
id = 2732, 평점 평균 =4.11
id = 2733, 평점 평균 =4.43
id = 2734, 평점 평균 =3.88
id = 2735, 평점 평균 =3.42
id = 2736, 평점 평균 =3.70
id = 2737, 평점 평균 =3.55
id = 2738, 평점 평균 =4.44
id = 2739, 평점 평균 =3.41
id = 2740, 평점 평균 =3.70
id = 2741, 평점 평균 =4.00
id = 2742, 평점 평균 =2.86
id = 2743, 

id = 3088, 평점 평균 =4.02
id = 3089, 평점 평균 =4.34
id = 3090, 평점 평균 =3.65
id = 3091, 평점 평균 =3.75
id = 3092, 평점 평균 =4.02
id = 3093, 평점 평균 =3.80
id = 3094, 평점 평균 =3.66
id = 3095, 평점 평균 =3.90
id = 3096, 평점 평균 =4.11
id = 3097, 평점 평균 =3.63
id = 3098, 평점 평균 =3.37
id = 3099, 평점 평균 =3.28
id = 3100, 평점 평균 =4.20
id = 3101, 평점 평균 =4.15
id = 3102, 평점 평균 =3.44
id = 3103, 평점 평균 =4.13
id = 3104, 평점 평균 =3.90
id = 3105, 평점 평균 =3.99
id = 3106, 평점 평균 =4.16
id = 3107, 평점 평균 =3.56
id = 3108, 평점 평균 =3.69
id = 3109, 평점 평균 =3.53
id = 3110, 평점 평균 =3.60
id = 3111, 평점 평균 =3.24
id = 3112, 평점 평균 =3.39
id = 3113, 평점 평균 =3.68
id = 3114, 평점 평균 =3.34
id = 3115, 평점 평균 =3.42
id = 3116, 평점 평균 =3.64
id = 3117, 평점 평균 =4.30
id = 3118, 평점 평균 =3.54
id = 3119, 평점 평균 =3.38
id = 3120, 평점 평균 =3.62
id = 3121, 평점 평균 =3.47
id = 3122, 평점 평균 =3.11
id = 3123, 평점 평균 =3.56
id = 3124, 평점 평균 =3.42
id = 3125, 평점 평균 =3.73
id = 3126, 평점 평균 =3.77
id = 3127, 평점 평균 =4.12
id = 3128, 평점 평균 =3.52
id = 3129, 평점 평균 =3.27
id = 3130, 평점 평균 =3.63
id = 3131, 

id = 3471, 평점 평균 =3.17
id = 3472, 평점 평균 =4.04
id = 3473, 평점 평균 =3.99
id = 3474, 평점 평균 =4.43
id = 3475, 평점 평균 =3.02
id = 3476, 평점 평균 =2.62
id = 3477, 평점 평균 =3.96
id = 3478, 평점 평균 =3.38
id = 3479, 평점 평균 =3.59
id = 3480, 평점 평균 =3.79
id = 3481, 평점 평균 =3.98
id = 3482, 평점 평균 =3.80
id = 3483, 평점 평균 =3.81
id = 3484, 평점 평균 =2.97
id = 3485, 평점 평균 =4.25
id = 3486, 평점 평균 =4.08
id = 3487, 평점 평균 =3.53
id = 3488, 평점 평균 =2.81
id = 3489, 평점 평균 =2.88
id = 3490, 평점 평균 =3.89
id = 3491, 평점 평균 =3.82
id = 3492, 평점 평균 =3.92
id = 3493, 평점 평균 =3.58
id = 3494, 평점 평균 =3.57
id = 3495, 평점 평균 =3.29
id = 3496, 평점 평균 =3.76
id = 3497, 평점 평균 =4.18
id = 3498, 평점 평균 =3.76
id = 3499, 평점 평균 =3.49
id = 3500, 평점 평균 =3.74
id = 3501, 평점 평균 =4.21
id = 3502, 평점 평균 =4.39
id = 3503, 평점 평균 =4.09
id = 3504, 평점 평균 =3.52
id = 3505, 평점 평균 =3.62
id = 3506, 평점 평균 =4.29
id = 3507, 평점 평균 =3.26
id = 3508, 평점 평균 =3.69
id = 3509, 평점 평균 =2.98
id = 3510, 평점 평균 =3.69
id = 3511, 평점 평균 =3.88
id = 3512, 평점 평균 =3.58
id = 3513, 평점 평균 =3.41
id = 3514, 

id = 3842, 평점 평균 =3.69
id = 3843, 평점 평균 =2.67
id = 3844, 평점 평균 =4.08
id = 3845, 평점 평균 =4.12
id = 3846, 평점 평균 =3.96
id = 3847, 평점 평균 =2.73
id = 3848, 평점 평균 =4.15
id = 3849, 평점 평균 =3.15
id = 3850, 평점 평균 =3.87
id = 3851, 평점 평균 =3.12
id = 3852, 평점 평균 =4.44
id = 3853, 평점 평균 =4.25
id = 3854, 평점 평균 =4.05
id = 3855, 평점 평균 =3.71
id = 3856, 평점 평균 =3.94
id = 3857, 평점 평균 =3.93
id = 3858, 평점 평균 =4.28
id = 3859, 평점 평균 =3.41
id = 3860, 평점 평균 =3.65
id = 3861, 평점 평균 =3.98
id = 3862, 평점 평균 =3.88
id = 3863, 평점 평균 =3.76
id = 3864, 평점 평균 =4.52
id = 3865, 평점 평균 =2.84
id = 3866, 평점 평균 =3.64
id = 3867, 평점 평균 =4.00
id = 3868, 평점 평균 =3.44
id = 3869, 평점 평균 =2.96
id = 3870, 평점 평균 =3.85
id = 3871, 평점 평균 =3.30
id = 3872, 평점 평균 =4.48
id = 3873, 평점 평균 =3.70
id = 3874, 평점 평균 =3.92
id = 3875, 평점 평균 =3.72
id = 3876, 평점 평균 =3.57
id = 3877, 평점 평균 =4.41
id = 3878, 평점 평균 =3.95
id = 3879, 평점 평균 =3.30
id = 3880, 평점 평균 =3.47
id = 3881, 평점 평균 =3.59
id = 3882, 평점 평균 =3.73
id = 3883, 평점 평균 =3.25
id = 3884, 평점 평균 =2.77
id = 3885, 

id = 4214, 평점 평균 =3.87
id = 4215, 평점 평균 =4.00
id = 4216, 평점 평균 =4.07
id = 4217, 평점 평균 =4.01
id = 4218, 평점 평균 =3.55
id = 4219, 평점 평균 =3.78
id = 4220, 평점 평균 =3.52
id = 4221, 평점 평균 =4.15
id = 4222, 평점 평균 =3.95
id = 4223, 평점 평균 =3.35
id = 4224, 평점 평균 =3.87
id = 4225, 평점 평균 =3.66
id = 4226, 평점 평균 =3.78
id = 4227, 평점 평균 =2.70
id = 4228, 평점 평균 =3.65
id = 4229, 평점 평균 =3.63
id = 4230, 평점 평균 =3.95
id = 4231, 평점 평균 =3.42
id = 4232, 평점 평균 =3.83
id = 4233, 평점 평균 =3.76
id = 4234, 평점 평균 =3.89
id = 4235, 평점 평균 =3.77
id = 4236, 평점 평균 =4.10
id = 4237, 평점 평균 =3.87
id = 4238, 평점 평균 =3.42
id = 4239, 평점 평균 =4.12
id = 4240, 평점 평균 =3.94
id = 4241, 평점 평균 =4.05
id = 4242, 평점 평균 =3.82
id = 4243, 평점 평균 =4.06
id = 4244, 평점 평균 =3.55
id = 4245, 평점 평균 =3.63
id = 4246, 평점 평균 =3.78
id = 4247, 평점 평균 =3.13
id = 4248, 평점 평균 =3.76
id = 4249, 평점 평균 =3.23
id = 4250, 평점 평균 =3.92
id = 4251, 평점 평균 =3.57
id = 4252, 평점 평균 =3.26
id = 4253, 평점 평균 =3.42
id = 4254, 평점 평균 =4.42
id = 4255, 평점 평균 =4.12
id = 4256, 평점 평균 =3.85
id = 4257, 

id = 4605, 평점 평균 =3.19
id = 4606, 평점 평균 =3.47
id = 4607, 평점 평균 =3.89
id = 4608, 평점 평균 =3.70
id = 4609, 평점 평균 =3.01
id = 4610, 평점 평균 =3.22
id = 4611, 평점 평균 =3.28
id = 4612, 평점 평균 =3.58
id = 4613, 평점 평균 =4.05
id = 4614, 평점 평균 =3.95
id = 4615, 평점 평균 =3.55
id = 4616, 평점 평균 =3.97
id = 4617, 평점 평균 =3.16
id = 4618, 평점 평균 =3.54
id = 4619, 평점 평균 =3.44
id = 4620, 평점 평균 =3.82
id = 4621, 평점 평균 =3.46
id = 4622, 평점 평균 =3.52
id = 4623, 평점 평균 =3.97
id = 4624, 평점 평균 =3.95
id = 4625, 평점 평균 =3.42
id = 4626, 평점 평균 =3.56
id = 4627, 평점 평균 =3.89
id = 4628, 평점 평균 =3.60
id = 4629, 평점 평균 =3.38
id = 4630, 평점 평균 =3.79
id = 4631, 평점 평균 =3.60
id = 4632, 평점 평균 =3.91
id = 4633, 평점 평균 =3.98
id = 4634, 평점 평균 =4.81
id = 4635, 평점 평균 =3.75
id = 4636, 평점 평균 =2.00
id = 4637, 평점 평균 =3.58
id = 4638, 평점 평균 =2.89
id = 4639, 평점 평균 =4.29
id = 4640, 평점 평균 =2.66
id = 4641, 평점 평균 =4.03
id = 4642, 평점 평균 =3.70
id = 4643, 평점 평균 =3.04
id = 4644, 평점 평균 =3.43
id = 4645, 평점 평균 =4.17
id = 4646, 평점 평균 =3.13
id = 4647, 평점 평균 =3.49
id = 4648, 

id = 4976, 평점 평균 =3.36
id = 4977, 평점 평균 =3.09
id = 4978, 평점 평균 =3.69
id = 4979, 평점 평균 =2.97
id = 4980, 평점 평균 =3.57
id = 4981, 평점 평균 =4.05
id = 4982, 평점 평균 =4.62
id = 4983, 평점 평균 =3.94
id = 4984, 평점 평균 =3.34
id = 4985, 평점 평균 =3.80
id = 4986, 평점 평균 =4.37
id = 4987, 평점 평균 =3.52
id = 4988, 평점 평균 =3.85
id = 4989, 평점 평균 =3.88
id = 4990, 평점 평균 =4.28
id = 4991, 평점 평균 =3.45
id = 4992, 평점 평균 =3.86
id = 4993, 평점 평균 =3.85
id = 4994, 평점 평균 =4.27
id = 4995, 평점 평균 =3.46
id = 4996, 평점 평균 =3.96
id = 4997, 평점 평균 =3.21
id = 4998, 평점 평균 =4.09
id = 4999, 평점 평균 =4.00
id = 5000, 평점 평균 =4.32
id = 5001, 평점 평균 =4.10
id = 5002, 평점 평균 =3.41
id = 5003, 평점 평균 =4.52
id = 5004, 평점 평균 =3.80
id = 5005, 평점 평균 =3.39
id = 5006, 평점 평균 =4.38
id = 5007, 평점 평균 =4.43
id = 5008, 평점 평균 =4.17
id = 5009, 평점 평균 =4.08
id = 5010, 평점 평균 =4.10
id = 5011, 평점 평균 =3.92
id = 5012, 평점 평균 =3.40
id = 5013, 평점 평균 =3.93
id = 5014, 평점 평균 =3.34
id = 5015, 평점 평균 =3.95
id = 5016, 평점 평균 =2.97
id = 5017, 평점 평균 =4.13
id = 5018, 평점 평균 =4.01
id = 5019, 

id = 5351, 평점 평균 =3.88
id = 5352, 평점 평균 =3.71
id = 5353, 평점 평균 =3.80
id = 5354, 평점 평균 =3.67
id = 5355, 평점 평균 =3.62
id = 5356, 평점 평균 =3.49
id = 5357, 평점 평균 =3.88
id = 5358, 평점 평균 =4.04
id = 5359, 평점 평균 =3.70
id = 5360, 평점 평균 =3.45
id = 5361, 평점 평균 =3.62
id = 5362, 평점 평균 =3.09
id = 5363, 평점 평균 =4.34
id = 5364, 평점 평균 =3.86
id = 5365, 평점 평균 =3.79
id = 5366, 평점 평균 =3.54
id = 5367, 평점 평균 =2.69
id = 5368, 평점 평균 =3.21
id = 5369, 평점 평균 =3.72
id = 5370, 평점 평균 =2.63
id = 5371, 평점 평균 =4.10
id = 5372, 평점 평균 =4.00
id = 5373, 평점 평균 =3.97
id = 5374, 평점 평균 =3.69
id = 5375, 평점 평균 =4.48
id = 5376, 평점 평균 =3.75
id = 5377, 평점 평균 =3.70
id = 5378, 평점 평균 =3.67
id = 5379, 평점 평균 =3.81
id = 5380, 평점 평균 =3.05
id = 5381, 평점 평균 =4.00
id = 5382, 평점 평균 =3.93
id = 5383, 평점 평균 =4.00
id = 5384, 평점 평균 =4.41
id = 5385, 평점 평균 =4.00
id = 5386, 평점 평균 =3.81
id = 5387, 평점 평균 =3.55
id = 5388, 평점 평균 =3.96
id = 5389, 평점 평균 =3.36
id = 5390, 평점 평균 =3.86
id = 5391, 평점 평균 =3.43
id = 5392, 평점 평균 =4.14
id = 5393, 평점 평균 =3.19
id = 5394, 

id = 5782, 평점 평균 =3.65
id = 5783, 평점 평균 =4.08
id = 5784, 평점 평균 =3.59
id = 5785, 평점 평균 =4.28
id = 5786, 평점 평균 =3.44
id = 5787, 평점 평균 =3.70
id = 5788, 평점 평균 =2.70
id = 5789, 평점 평균 =3.91
id = 5790, 평점 평균 =3.72
id = 5791, 평점 평균 =4.09
id = 5792, 평점 평균 =3.65
id = 5793, 평점 평균 =4.17
id = 5794, 평점 평균 =3.75
id = 5795, 평점 평균 =3.06
id = 5796, 평점 평균 =3.58
id = 5797, 평점 평균 =3.52
id = 5798, 평점 평균 =3.71
id = 5799, 평점 평균 =3.72
id = 5800, 평점 평균 =3.30
id = 5801, 평점 평균 =3.93
id = 5802, 평점 평균 =4.08
id = 5803, 평점 평균 =2.83
id = 5804, 평점 평균 =3.62
id = 5805, 평점 평균 =4.07
id = 5806, 평점 평균 =3.86
id = 5807, 평점 평균 =3.85
id = 5808, 평점 평균 =4.30
id = 5809, 평점 평균 =3.79
id = 5810, 평점 평균 =3.86
id = 5811, 평점 평균 =3.44
id = 5812, 평점 평균 =3.59
id = 5813, 평점 평균 =3.69
id = 5814, 평점 평균 =4.00
id = 5815, 평점 평균 =3.88
id = 5816, 평점 평균 =3.66
id = 5817, 평점 평균 =4.12
id = 5818, 평점 평균 =3.47
id = 5819, 평점 평균 =3.80
id = 5820, 평점 평균 =3.44
id = 5821, 평점 평균 =3.87
id = 5822, 평점 평균 =3.63
id = 5823, 평점 평균 =4.02
id = 5824, 평점 평균 =3.24
id = 5825, 

In [152]:
print('각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기')

moreThan4 = []
for i in np.unique(user_id):
    mean = np.mean(data[user_id == i ][:,2])
    if mean >= 4:
        moreThan4.append(i)
print(f'각 사용자별 평균 평점이 4점 이상인 사용자: {moreThan4}')
print(f' 인원수 : {len(moreThan4)} 명')


print('각 사용자별 평균 평점이 4점 이상인 사용자:',np.sum(id_avg_rating[:,1]>=4))

각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기
각 사용자별 평균 평점이 4점 이상인 사용자: [1, 4, 7, 10, 17, 20, 27, 36, 43, 46, 53, 54, 55, 64, 65, 67, 69, 74, 75, 76, 81, 82, 86, 88, 91, 97, 101, 103, 105, 106, 109, 112, 121, 124, 125, 126, 128, 129, 130, 138, 150, 152, 153, 156, 158, 161, 162, 164, 171, 177, 183, 184, 186, 187, 189, 196, 205, 210, 213, 215, 220, 222, 228, 230, 231, 233, 234, 235, 239, 244, 246, 248, 252, 255, 257, 259, 265, 266, 270, 274, 275, 283, 285, 288, 291, 297, 299, 300, 307, 309, 311, 313, 316, 320, 322, 325, 330, 332, 336, 339, 341, 343, 345, 346, 356, 366, 367, 372, 374, 375, 376, 379, 381, 382, 399, 404, 408, 412, 413, 417, 420, 421, 427, 434, 437, 444, 446, 447, 450, 451, 452, 455, 466, 469, 472, 473, 485, 486, 494, 496, 502, 503, 505, 514, 518, 521, 523, 525, 527, 529, 530, 537, 538, 543, 553, 564, 567, 568, 574, 577, 582, 583, 584, 586, 588, 589, 590, 592, 594, 597, 605, 606, 607, 609, 615, 617, 623, 625, 626, 630, 634, 635, 636, 638, 640, 641, 642, 645, 653, 657, 661, 664, 671, 67